# Generated by Django 2.1.3 on 2018-11-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('location_type', models.CharField(choices=[('FO', 'Forest'), ('DE', 'Desert'), ('DU', 'Dungeon'), ('RI', 'River'), ('OC', 'Ocean')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('player_class', models.CharField(choices=[('KN', 'Knight'), ('WI', 'Wizard'), ('TH', 'Thief'), ('PA', 'Paladin')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('level', models.IntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valarmorghulis.Location')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='player_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='valarmorghulis.Player'),
        ),
        migrations.AddField(
            model_name='message',
            name='player_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='valarmorghulis.Player'),
        ),
    ]
