# Generated by Django 2.1.3 on 2018-11-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valarmorghulis', '0002_auto_20181107_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('Forest', 'Forest'), ('Desert', 'Desert'), ('Dungeon', 'Dungeon'), ('River', 'River'), ('Ocean', 'Ocean')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_class',
            field=models.CharField(choices=[('Knight', 'Knight'), ('Wizard', 'Wizard'), ('Thief', 'Thief'), ('Paladin', 'Paladin')], max_length=10),
        ),
    ]
